name: Deploy Infrastructure

on:
  push:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TF_ACTION_WORKING_DIR: 'terraform_code'
  AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.SECRET_ACCESS_KEY }}
  BUCKET_TF_STATE: "terraform-markuc"
jobs:
  tf_fmt:
    name: Deploy Infra
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.4
      

    - name: Terraform Init
      id: init
      run: terraform init -var-file ./lab.tfvars -backend-config="bucket=$BUCKET_TF_STATE"
      working-directory: ./terraform_code
    - name: Terraform Validate
      id: Validate
      run: terraform validate
      working-directory: ./terraform_code

    - name: Terraform Apply
      run: terraform apply -var-file ./lab.tfvars -auto-approve -input=false
      working-directory: ./terraform_code